name: price
description: "daily price list"
publish_to:
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  cloud_firestore:
  path_provider:
  hive:
  hive_flutter:
  cupertino_icons: ^1.0.6
  fl_chart:
  firebase_auth:
  firebase_messaging:
  lottie:
  flutter_overlay_loader:
  flutter_secure_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/Baby Kailan.png
    - assets/Lady finger.png
    - assets/Baby Susu.png
    - assets/Leeks.png
    - assets/Basil.png
    - assets/Lobak.png
    - assets/Bayam merah.png
    - assets/Lobak (B).png
    - assets/Bayam.png
    - assets/Mint.png
    - assets/Beetroot.png
    - assets/Parsley.png
    - assets/Broccoli.png
    - assets/Petai.png
    - assets/Cabbage (A).png
    - assets/Pochoy.png
    - assets/Cabbage (B).png
    - assets/Potatoes.png
    - assets/Cabbage (M).png
    - assets/Pumpkin.png
    - assets/Cabbage Bunga.png
    - assets/Red Chilli (A).png
    - assets/Capsicum Green (A).png
    - assets/Red Chilli (B).png
    - assets/Capsicum Green (B).png
    - assets/Red Coral.png
    - assets/Capsicum Red (A).png
    - assets/Red onion.png
    - assets/Capsicum Red (B).png
    - assets/Romaine.png
    - assets/Capsicum Yellow (A).png
    - assets/Sawi Jepun.png
    - assets/Capsicum Yellow (B).png
    - assets/Sawi Panjang.png
    - assets/Carrot A.png
    - assets/Sawi Susu.png
    - assets/Carrot B.png
    - assets/Strawberry (A).png
    - assets/Cauliflower.png
    - assets/Strawberry (B).png
    - assets/Cherry B.png
    - assets/Cherry A.png
    - assets/Sweet Corn - A.png
    - assets/Cherry Tomato - RED.png
    - assets/Sweet Corn - AA.png
    - assets/Cherry Tomato - YELLOW.png
    - assets/Sweet Corn - B.png
    - assets/Chinese Cabbage (A).png
    - assets/Sweet Corn - C.png
    - assets/Chinese Cabbage (B).png
    - assets/Terung Mini (A).png
    - assets/Chives - Big.png
    - assets/Terung Mini (AA).png
    - assets/Chives - Small.png
    - assets/Terung Mini (B).png
    - assets/Daun Bawang.png
    - assets/Terung Mutiara (A).png
    - assets/Daun Soup.png
    - assets/Terung Mutiara (AA).png
    - assets/Daun Ubi.png
    - assets/Terung Panjang (A).png
    - assets/Egg Plant.png
    - assets/Terung Panjang (AA).png
    - assets/Flat Bean.png
    - assets/Terung Panjang (B).png
    - assets/Flat Bean- Long.png
    - assets/Timun Jepun (A).png
    - assets/French Bean (B).png
    - assets/Timun Jepun (B).png
    - assets/French Beans (A).png
    - assets/Timun Mini.png
    - assets/Garlic pealed.png
    - assets/Timun Tua.png
    - assets/Green Chilli (A).png
    - assets/Tomato (L).png
    - assets/Green Chilli (B).png
    - assets/Tomato (M).png
    - assets/Green Coral.png
    - assets/Tomato (S).png
    - assets/Halia muda.png
    - assets/Tomato (XL).png
    - assets/Iceberg.png
    - assets/You Mak Tam.png
    - assets/Icikuwa.png
    - assets/Zucchini Green.png
    - assets/Insai - Coriander.png
    - assets/Zucchini Green (B).png
    - assets/Kacang panjang.png
    - assets/Zucchini Yellow.png
    - assets/Kaichoy.png
    - assets/Zucchini Yellow (B).png
    - assets/Kailan Cameron.png
    - assets/Kang kung.png
    - assets/Kunyit.png
    - assets/Labu air.png
    - assets/Labu Cameron.png
    - assets/gif/live.gif
    - assets/spinner.json